CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    customer_name_or_label VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    opened_by_user_id BIGINT NOT NULL,
    closed_by_user_id BIGINT,
    opened_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,
    notes VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_orders_code UNIQUE (code),
    CONSTRAINT fk_orders_opened_by_user FOREIGN KEY (opened_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_orders_closed_by_user FOREIGN KEY (closed_by_user_id) REFERENCES users (id)
);

CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_opened_at ON orders (opened_at);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name_snapshot VARCHAR(255) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_order_items_subtotal_positive CHECK (subtotal > 0)
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    sold_at TIMESTAMP NOT NULL,
    opened_by_user_id BIGINT NOT NULL,
    closed_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_sales_order_id UNIQUE (order_id),
    CONSTRAINT fk_sales_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_sales_opened_by_user FOREIGN KEY (opened_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_sales_closed_by_user FOREIGN KEY (closed_by_user_id) REFERENCES users (id),
    CONSTRAINT ck_sales_total_amount_positive CHECK (total_amount > 0)
);

CREATE INDEX idx_sales_sold_at ON sales (sold_at);

CREATE TABLE sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name_snapshot VARCHAR(255) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) REFERENCES sales (id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_sale_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_sale_items_subtotal_positive CHECK (subtotal > 0)
);

CREATE INDEX idx_sale_items_sale_id ON sale_items (sale_id);
