CREATE TABLE store_credits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_name VARCHAR(255) NOT NULL,
    buyer_phone VARCHAR(50) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    credit_date DATE NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_store_credits_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_store_credits_due_date_valid CHECK (due_date >= credit_date)
);

CREATE INDEX idx_store_credits_status ON store_credits (status);
CREATE INDEX idx_store_credits_credit_date ON store_credits (credit_date);
CREATE INDEX idx_store_credits_due_date ON store_credits (due_date);

CREATE TABLE store_credit_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_credit_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name_snapshot VARCHAR(255) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_store_credit_items_store_credit FOREIGN KEY (store_credit_id)
        REFERENCES store_credits (id) ON DELETE CASCADE,
    CONSTRAINT fk_store_credit_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_store_credit_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_store_credit_items_subtotal_positive CHECK (subtotal > 0)
);

CREATE INDEX idx_store_credit_items_store_credit_id ON store_credit_items (store_credit_id);
